from .anyup import AnyUpsampler
from .base import BaseUpsampler
from .bilinear import Bilinear
from .featup import FeatUp
from .ircnn import IRCNN
from .jafar import JAFAR
from .jbf import JBF
from .jbu import JBU
from .naf import NAF
from .nearest import Nearest
from .rednet import REDNet
from .restormer import Restormer
